openapi: 3.0.3
info:
  title: EE461L Project
  description: This is the API for our EE461L Project
  version: 1.0.0

servers:
  - url: http://localhost:5000

tags:
  - name: users
    description: Endpoints regarding user management
  - name: projects
    description: Endpoints regarding projects

paths:
  /users/login:
    $ref: ./EndpointDocumentation/Users/login.yml
  /users/register:
    $ref: ./EndpointDocumentation/Users/register.yml
  /projects/:
    $ref: ./EndpointDocumentation/Projects/projects.yml
  /projects/{project_id}:
    $ref: ./EndpointDocumentation/Projects/project_w_id.yml
  /projects/{project_oid}:
    $ref: ./EndpointDocumentation/Projects/project_w_oid.yml
