name: Deploy Frontend

on:
  push:
    branches:
      - main
      - frontend/fixing-deploying
  pull_request:
    branches:
      - main
      - frontend/fixing-deploying

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ee461l-final-project-group-2" #Must be unique in Heroku
          heroku_email: "maxwithrow2222@gmail.com"
          appdir: "client"
          usedocker: true
